//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HillsboroughEducation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criteria
    {
        public long SCHL_SEQ { get; set; }
        public string DESCR { get; set; }
        public bool APPLICATION_IND { get; set; }
        public bool REQUIRED { get; set; }
        public bool ACTIVE { get; set; }
    
        public virtual Scholarships Scholarships { get; set; }
    }
}
