//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HillsboroughEducation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eligible
    {
        public string STUDENT_ID { get; set; }
        public long SCHL_SEQ { get; set; }
        public Nullable<bool> APPLIED { get; set; }
        public Nullable<System.DateTime> APPLIED_DATE { get; set; }
    
        public virtual Scholarships Scholarships { get; set; }
        public virtual Students Students { get; set; }
    }
}
