//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HillsboroughEducation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public bool QUESTION_SEQ { get; set; }
        public string DESCR { get; set; }
        public string SCHL_TYPE { get; set; }
        public Nullable<long> PREV_SEQ { get; set; }
        public Nullable<long> NEXT_SEQ { get; set; }
    }
}
