//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HillsboroughEducation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviewers
    {
        public long USER_SEQ { get; set; }
        public Nullable<int> ACADEMIC_YEAR { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string COUNTRY { get; set; }
        public string GENDER { get; set; }
        public string ADDRESS_LINE1 { get; set; }
        public string ADDRESS_LINE2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string COUNTY { get; set; }
        public Nullable<int> POSTAL_CODE { get; set; }
        public string HOME_PHONE { get; set; }
        public string WORK_PHONE { get; set; }
        public string CELL_PHONE { get; set; }
        public string EMAIL { get; set; }
        public string NOTES { get; set; }
        public Nullable<bool> BAD_EMAIL { get; set; }
        public Nullable<int> ORG_SEQ { get; set; }
        public int REVIEWER_ID { get; set; }
    }
}
